package com.example.smarttextvision.data

import androidx.room.*

/**
 * Represents a message entity in the local database.
 *
 * This entity stores information about individual messages exchanged between users.
 * It includes the message content, sender and receiver IDs, and a timestamp.
 *
 * @property id The unique identifier for the message. Auto-generated by the database.
 * @property senderId The ID of the user who sent the message. This is a foreign key referencing [UserEntity].
 * @property receiverId The ID of the user who received the message. This is a foreign key referencing [UserEntity].
 * @property content The text content of the message.
 * @property timestamp The timestamp indicating when the message was sent (e.g., milliseconds since epoch).
 *
 * @constructor Creates a new [MessageEntity] instance.
 *
 * @see UserEntity
 */
@Entity(tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity = UserEntity::class,
            parentColumns = ["id"],
            childColumns = ["senderId"],
            onDelete = ForeignKey.NO_ACTION
        ),
        ForeignKey(
            entity = UserEntity::class,
            parentColumns = ["id"],
            childColumns = ["receiverId"],
            onDelete = ForeignKey.NO_ACTION
        )
    ]
)
data class MessageEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val senderId: Long,
    val receiverId: Long,
    val content: String,
    val timestamp: Long
)